# Specify the full permission assignees for issues and pull requests
full_permission_assignees:
  - mmoshihud
  - fahim37

# Set to true if you want to overwrite default permissions with full permissions
overwrite_default_permissions: true

# Set to true to add reviewers to PRs
addReviewers: true

# Set to 'author' to add PR's author as an assignee
addAssignees: author

# A list of reviewers to be added to PRs (GitHub username)
reviewers:
  - mmoshihud
  - fahim37

# A number of reviewers added to the PR
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 1

# A number of assignees to add to the PRs
# Set to 0 to add all the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 0