# Generated by Django 5.0.1 on 2024-02-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="height",
        ),
        migrations.RemoveField(
            model_name="product",
            name="width",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="height",
                null=True,
                upload_to="images/testimagemodel/",
                verbose_name="Image",
                width_field="width",
            ),
        ),
    ]
